const fs = require('node:fs');
const path = require('node:path');
const vm = require('node:vm');

const ROOT = path.resolve(__dirname, '..');
const DIST = path.join(ROOT, 'dist');

const ROOT_FILES = [
  '_headers',
  '_redirects',
  'app.js',
  'app-images.js',
  'index.html',
  'manifest.json',
  'recipe.html',
  'recipe.js',
  'recipes.js',
  'robots.txt',
  'service-worker.js',
  'sitemap.xml',
  'style.css'
];

const ASSET_FILES = [
  'base-du-site.png',
  'base-principale-fond-site.jpg',
  'catalog-1.js',
  'catalog-2.js',
  'catalog-3.js',
  'catalog-4.js',
  'cook-note-mark.svg',
  'cook-note-white.png',
  'cook-note.png'
];

const ASSET_DIRS = [
  'recipe-card-images',
  'recipe-images-optimized',
  'vendor'
];

function withinRoot(target) {
  const relative = path.relative(ROOT, target);
  return relative && !relative.startsWith('..') && !path.isAbsolute(relative);
}

function ensureParent(file) {
  fs.mkdirSync(path.dirname(file), { recursive: true });
}

function copyFile(relative) {
  const source = path.join(ROOT, relative);
  const destination = path.join(DIST, relative);
  if (!fs.existsSync(source)) throw new Error(`${relative}: fichier source introuvable.`);
  ensureParent(destination);
  fs.copyFileSync(source, destination);
}

function copyDirectory(relative) {
  const source = path.join(ROOT, relative);
  const destination = path.join(DIST, relative);
  if (!fs.existsSync(source)) throw new Error(`${relative}: dossier source introuvable.`);
  fs.cpSync(source, destination, { recursive: true });
}

function loadImageManifest() {
  const context = { window: {}, Object };
  vm.createContext(context);
  vm.runInContext(
    fs.readFileSync(path.join(ROOT, 'assets', 'image-manifest.js'), 'utf8'),
    context,
    { filename: path.join(ROOT, 'assets', 'image-manifest.js') }
  );
  return context.window.COOK_NOTE_IMAGE_MANIFEST || {};
}

function writeDistImageManifest() {
  const manifest = loadImageManifest();
  const productionManifest = Object.fromEntries(
    Object.entries(manifest)
      .filter(([file]) => !file.startsWith('assets/recipe-images/'))
      .sort(([left], [right]) => left.localeCompare(right, 'en'))
  );
  const text = `// Generated by scripts/build-site.js. Do not edit manually.\nwindow.COOK_NOTE_IMAGE_MANIFEST = Object.freeze(${JSON.stringify(productionManifest, null, 2)});\n`;
  const destination = path.join(DIST, 'assets', 'image-manifest.js');
  ensureParent(destination);
  fs.writeFileSync(destination, text, 'utf8');
}

if (!withinRoot(DIST)) {
  throw new Error(`Dossier dist invalide: ${DIST}`);
}

fs.rmSync(DIST, { recursive: true, force: true });
fs.mkdirSync(DIST, { recursive: true });

ROOT_FILES.forEach(copyFile);
ASSET_FILES.forEach(file => copyFile(path.join('assets', file)));
ASSET_DIRS.forEach(dir => copyDirectory(path.join('assets', dir)));
writeDistImageManifest();

console.log('Build Cook Note OK: dist/');
